import type {
  PathRedirectMapping,
  PostSlugRedirectMapping,
  RedirectConfiguration,
  RedirectRule,
} from "@/lib/redirects/types";

function validatePath({ from, to }: PathRedirectMapping): void {
  for (const [name, value] of [
    ["source", from],
    ["target", to],
  ] as const) {
    if (!value.startsWith("/") || /\s/u.test(value) || /[?#]/u.test(value)) {
      throw new Error(
        `Redirect ${name} must be a clean absolute path: ${value}`,
      );
    }
  }
  if (from === to) {
    throw new Error(`Redirect source and target are identical: ${from}`);
  }
}

function validateSlug({ from, to }: PostSlugRedirectMapping): void {
  for (const [name, value] of [
    ["source", from],
    ["target", to],
  ] as const) {
    if (!value || /[\s/?#]/u.test(value)) {
      throw new Error(`Post redirect ${name} must be one URL slug: ${value}`);
    }
  }
  if (from === to) {
    throw new Error(`Post redirect source and target are identical: ${from}`);
  }
}

export function createRedirectRules(
  configuration: RedirectConfiguration,
): readonly RedirectRule[] {
  const rules: RedirectRule[] = [];
  const sources = new Set<string>();

  const addRule = (mapping: PathRedirectMapping) => {
    validatePath(mapping);
    if (sources.has(mapping.from)) {
      throw new Error(`Duplicate redirect source: ${mapping.from}`);
    }
    sources.add(mapping.from);
    rules.push({ ...mapping, status: 301 });
  };

  for (const mapping of configuration.paths) addRule(mapping);
  for (const mapping of configuration.postSlugs) {
    validateSlug(mapping);
    const target = `/posts/${mapping.to}/`;
    addRule({ from: `/posts/${mapping.from}`, to: target });
    addRule({ from: `/posts/${mapping.from}/`, to: target });
  }

  for (const rule of rules) {
    if (sources.has(rule.to)) {
      throw new Error(
        `Redirect target creates a chain through another source: ${rule.to}`,
      );
    }
  }

  return rules;
}

export function serializeRedirectRule(rule: RedirectRule): string {
  return `${rule.from} ${rule.to} ${rule.status}`;
}

export function serializeRedirectFile(
  configuration: RedirectConfiguration,
): string {
  const rules = createRedirectRules(configuration);
  return [
    "# Generated from redirects.config.ts. Do not edit this file directly.",
    "# All migration redirects must stay one-hop and permanent.",
    ...rules.map(serializeRedirectRule),
    "",
  ].join("\n");
}
